### ISSUE TITLE
Incompatible with OTP 21 due to dependency (director)

### ISSUE THREAD

**Issue by cblage** [emeter/emeter#1]
Looking at the director repo, I'm not sure if it's being maintained right now. Currently I can "fix" the incompatibility issue by using my fork of director, but I'm not sure this is a great long-term solution.

```
{:director, github: "aruki-delivery/director", tag: "19.0.0", override: true},
```

https://github.com/radarjones/director/pull/1

**Comment by Pouriya-Jahanbakhsh** [comment]
Hello friend. Thank you for opening this issue. I have a plan to update director and be compatible with 21 for next 3 months. Also I will update this and add hooking feature for adding new plugins. If you can use your fork for now, It's great.

**Comment by cblage** [comment]
Sounds good!

**Comment by Pouriya-Jahanbakhsh** [comment]
Now director is compatible with OTP 21. new release : [**18.9.30**](https://github.com/Pouriya-Jahanbakhsh/director/releases/tag/18.9.30)

**Comment by cblage** [comment]
Besides it being missing in hex.pm. awesome :D

**Comment by Pouriya-Jahanbakhsh** [comment]
I tried to publish new release using rebar3 v 3.6.2. But there was a bug in rebar3 :-S

**Comment by cblage** [comment]
?

**Comment by Pouriya-Jahanbakhsh** [comment]
I figured it out. Unfortunately [hex.pm](https://hex.pm) (Actually google) does not allow my country connect to it:
```sh
pouriya@codefather /p $ curl hex.pm
```
```html5
<!DOCTYPE html>
<html lang=en>
  ...
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/</code> from this server.  <ins>That’s all we know.</ins>
```
So I used VPN and the problem solved !

**Comment by cblage** [comment]
Awesomeness, thanks!
